Dir             := A_ScriptDir "\Includes\UserCommands.ahk" ;~ Dir Variables for Title Notification Function
TmpDir          := A_ScriptDir "\tmpscrpts"                 ;~ Variable for Force Restart Script
Icon_MSCDefault := A_ScriptDir "\Icon.ico"
Icon_AHK        := A_Dropbox "\AHK Scripts\_DMD Scripts\_Master Script\Resources\Master If Commands Icons\AHK.ico"
Icon_Dorico     := A_ProgramFiles64 "\Steinberg\Dorico3.5\Dorico3.5.exe"
Icon_Facebook   := A_GoogleDrive "\Folder Icons\IOS Icons\Icons_Yosemite_1024px\Facebook.ico,1"
Icon_Kontakt    := A_ProgramFiles64 "\Native Instruments\Kontakt\Kontakt.exe"
Icon_Signal     := A_AppDataLocal "\Programs\signal-desktop\Signal.exe"
Icon_YouTube    := A_GoogleDrive "\Folder Icons\IOS Icons\Icons_Yosemite_1024px\YouTube.ico"