if(1){ ;~ Tomorrow Night Color Definitions:
	Global cBackground   := "c" . "1d1f21"
	Global cCurrentLine  := "c" . "282a2e"
	Global cSelection    := "c" . "373b41"
	Global cForeground   := "c" . "c5c8c6"
	Global cComment      := "c" . "969896"
	Global cRed          := "c" . "cc6666"
	Global cOrange       := "c" . "de935f"
	Global cYellow       := "c" . "f0c674"
	Global cGreen        := "c" . "b5bd68"
	Global cAqua         := "c" . "8abeb7"
	Global cBlue         := "c" . "81a2be"
	Global cPurple       := "c" . "b294bb"
}
if(){ ;~ Tomorrow
	Global cBackground   := "c" . "ffffff"
	Global cCurrentLine  := "c" . "efefef"
	Global cSelection    := "c" . "d6d6d6"
	Global cForeground   := "c" . "4d4d4c"
	Global cComment      := "c" . "8e908c"
	Global cRed          := "c" . "c82829"
	Global cOrange       := "c" . "f5871f"
	Global cYellow       := "c" . "eab700"
	Global cGreen        := "c" . "718c00"
	Global cAqua         := "c" . "3e999f"
	Global cBlue         := "c" . "4271ae"
	Global cPurple       := "c" . "8959a8"
}
if(){ ;~ Tomorrow Night Eighties
	Global cBackground   := "c" . "2d2d2d"
	Global cCurrentLine  := "c" . "393939"
	Global cSelection    := "c" . "515151"
	Global cForeground   := "c" . "cccccc"
	Global cComment      := "c" . "999999"
	Global cRed          := "c" . "f2777a"
	Global cOrange       := "c" . "f99157"
	Global cYellow       := "c" . "ffcc66"
	Global cGreen        := "c" . "99cc99"
	Global cAqua         := "c" . "66cccc"
	Global cBlue         := "c" . "6699cc"
	Global cPurple       := "c" . "cc99cc"
}
if(){ ;~ Tomorrow Night Blue
	Global cBackground   := "c" . "002451"
	Global cCurrentLine  := "c" . "00346e"
	Global cSelection    := "c" . "003f8e"
	Global cForeground   := "c" . "ffffff"
	Global cComment      := "c" . "7285b7"
	Global cRed          := "c" . "ff9da4"
	Global cOrange       := "c" . "ffc58f"
	Global cYellow       := "c" . "ffeead"
	Global cGreen        := "c" . "d1f1a9"
	Global cAqua         := "c" . "99ffff"
	Global cBlue         := "c" . "bbdaff"
	Global cPurple       := "c" . "ebbbff"
}
if(){ ;~ Tomorrow Night Bright
	Global cBackground   := "c" . "000000"
	Global cCurrentLine  := "c" . "2a2a2a"
	Global cSelection    := "c" . "424242"
	Global cForeground   := "c" . "eaeaea"
	Global cComment      := "c" . "969896"
	Global cRed          := "c" . "d54e53"
	Global cOrange       := "c" . "e78c45"
	Global cYellow       := "c" . "e7c547"
	Global cGreen        := "c" . "b9ca4a"
	Global cAqua         := "c" . "70c0b1"
	Global cBlue         := "c" . "7aa6da"
	Global cPurple       := "c" . "c397d8"
}